version: "3"

networks:
  laravel:

services:
  db:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lara_data
      MYSQL_USER: lara
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SEVICE_TAGS: dev
      SEVICE_NAME: mysql
    networks:
      - laravel

  web:
    tty: true
    image: docker.io/bitnami/laravel:8
    container_name: laravel
    environment:
      - DB_HOST=db
      - DB_USERNAME=lara
      - DB_DATABASE=lara_data
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
    networks:
      - laravel
